/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __CONTEXT_TEST_BPF_SKEL_H__
#define __CONTEXT_TEST_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct context_test_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *test_prog;
	} progs;
	struct {
		struct bpf_link *test_prog;
	} links;

#ifdef __cplusplus
	static inline struct context_test_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct context_test_bpf *open_and_load();
	static inline int load(struct context_test_bpf *skel);
	static inline int attach(struct context_test_bpf *skel);
	static inline void detach(struct context_test_bpf *skel);
	static inline void destroy(struct context_test_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
context_test_bpf__destroy(struct context_test_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
context_test_bpf__create_skeleton(struct context_test_bpf *obj);

static inline struct context_test_bpf *
context_test_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct context_test_bpf *obj;
	int err;

	obj = (struct context_test_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = context_test_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	context_test_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct context_test_bpf *
context_test_bpf__open(void)
{
	return context_test_bpf__open_opts(NULL);
}

static inline int
context_test_bpf__load(struct context_test_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct context_test_bpf *
context_test_bpf__open_and_load(void)
{
	struct context_test_bpf *obj;
	int err;

	obj = context_test_bpf__open();
	if (!obj)
		return NULL;
	err = context_test_bpf__load(obj);
	if (err) {
		context_test_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
context_test_bpf__attach(struct context_test_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
context_test_bpf__detach(struct context_test_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *context_test_bpf__elf_bytes(size_t *sz);

static inline int
context_test_bpf__create_skeleton(struct context_test_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "context_test_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "context_.rodata";
	s->maps[0].map = &obj->maps.rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "test_prog";
	s->progs[0].prog = &obj->progs.test_prog;
	s->progs[0].link = &obj->links.test_prog;

	s->data = context_test_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *context_test_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x09\0\x01\
\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x66\x65\x6e\
\x74\x72\x79\x2f\x64\x6f\x5f\x6e\x61\x6e\x6f\x73\x6c\x65\x65\x70\0\x6c\x69\x63\
\x65\x6e\x73\x65\0\x2e\x72\x6f\x64\x61\x74\x61\0\x63\x6f\x6e\x74\x65\x78\x74\
\x5f\x74\x65\x73\x74\x2e\x62\x70\x66\x2e\x63\0\x74\x65\x73\x74\x5f\x70\x72\x6f\
\x67\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x74\x65\x73\x74\x5f\x70\x72\x6f\x67\0\
\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x72\x65\x6c\x66\x65\x6e\x74\x72\x79\x2f\x64\
\x6f\x5f\x6e\x61\x6e\x6f\x73\x6c\x65\x65\x70\0\x2e\x42\x54\x46\0\x2e\x42\x54\
\x46\x2e\x65\x78\x74\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x35\0\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\0\0\0\x01\0\x05\0\0\0\0\0\0\0\0\0\x06\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5a\0\0\0\x12\
\0\x03\0\0\0\0\0\0\0\0\0\x30\0\0\0\0\0\0\0\x64\0\0\0\x11\0\x04\0\0\0\0\0\0\0\0\
\0\x0d\0\0\0\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x06\0\0\0\
\x85\0\0\0\x06\0\0\0\xb7\0\0\0\x01\0\0\0\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\
\x42\x53\x44\x2f\x47\x50\x4c\0\x68\x65\x6c\x6c\x6f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x01\0\0\0\x04\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\xe8\0\0\0\xe8\0\0\0\xc4\0\
\0\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\x01\0\0\x0d\x03\0\0\0\x01\0\0\0\x01\0\0\
\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x09\0\0\0\x01\0\0\x0c\x02\0\0\0\
\x13\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x05\0\0\0\
\x07\0\0\0\x0d\0\0\0\x18\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\x2c\0\0\0\0\0\0\
\x0e\x06\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x0a\x05\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\
\x09\0\0\0\x07\0\0\0\x06\0\0\0\x34\0\0\0\0\0\0\x0e\x0a\0\0\0\0\0\0\0\xa0\0\0\0\
\x01\0\0\x0f\x0d\0\0\0\x08\0\0\0\0\0\0\0\x0d\0\0\0\xa8\0\0\0\x01\0\0\x0f\x06\0\
\0\0\x0b\0\0\0\0\0\0\0\x06\0\0\0\0\x63\x74\x78\0\x69\x6e\x74\0\x74\x65\x73\x74\
\x5f\x70\x72\x6f\x67\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\
\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\x74\
\x65\x73\x74\x5f\x70\x72\x6f\x67\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x2f\x68\x6f\
\x6d\x65\x2f\x70\x72\x69\x79\x61\x2f\x6c\x69\x62\x62\x70\x66\x2d\x62\x6f\x6f\
\x74\x73\x74\x72\x61\x70\x2f\x65\x78\x61\x6d\x70\x6c\x65\x73\x2f\x63\x2f\x63\
\x6f\x6e\x74\x65\x78\x74\x5f\x74\x65\x73\x74\x2e\x62\x70\x66\x2e\x63\0\x62\x70\
\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x68\x65\x6c\x6c\x6f\x22\x29\x3b\0\x72\
\x65\x74\x75\x72\x6e\x20\x31\x3b\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x72\x6f\
\x64\x61\x74\x61\0\x66\x65\x6e\x74\x72\x79\x2f\x64\x6f\x5f\x6e\x61\x6e\x6f\x73\
\x6c\x65\x65\x70\0\0\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\
\x2c\0\0\0\x40\0\0\0\0\0\0\0\x08\0\0\0\xb0\0\0\0\x01\0\0\0\0\0\0\0\x04\0\0\0\
\x10\0\0\0\xb0\0\0\0\x02\0\0\0\0\0\0\0\x46\0\0\0\x81\0\0\0\x01\x20\0\0\x20\0\0\
\0\x46\0\0\0\x96\0\0\0\x01\x24\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x01\0\0\0\x03\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\
\x92\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x09\0\0\0\
\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd8\0\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x11\0\0\0\x01\0\0\0\x06\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x80\x01\0\0\0\0\0\0\x30\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x25\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\xb0\x01\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x2d\0\0\0\x01\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\xbd\x01\0\0\0\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x6c\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\x01\0\0\
\0\0\0\0\x10\0\0\0\0\0\0\0\x02\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\
\0\0\x84\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd8\x01\0\0\0\0\0\0\
\xc4\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x89\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x03\0\0\0\0\0\0\x60\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct context_test_bpf *context_test_bpf::open(const struct bpf_object_open_opts *opts) { return context_test_bpf__open_opts(opts); }
struct context_test_bpf *context_test_bpf::open_and_load() { return context_test_bpf__open_and_load(); }
int context_test_bpf::load(struct context_test_bpf *skel) { return context_test_bpf__load(skel); }
int context_test_bpf::attach(struct context_test_bpf *skel) { return context_test_bpf__attach(skel); }
void context_test_bpf::detach(struct context_test_bpf *skel) { context_test_bpf__detach(skel); }
void context_test_bpf::destroy(struct context_test_bpf *skel) { context_test_bpf__destroy(skel); }
const void *context_test_bpf::elf_bytes(size_t *sz) { return context_test_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
context_test_bpf__assert(struct context_test_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __CONTEXT_TEST_BPF_SKEL_H__ */
