/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __MAP_PERF_TEST2_BPF_SKEL_H__
#define __MAP_PERF_TEST2_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct map_perf_test2_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *pb;
		struct bpf_map *heap;
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *map_perf_test;
	} progs;
	struct {
		struct bpf_link *map_perf_test;
	} links;

#ifdef __cplusplus
	static inline struct map_perf_test2_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct map_perf_test2_bpf *open_and_load();
	static inline int load(struct map_perf_test2_bpf *skel);
	static inline int attach(struct map_perf_test2_bpf *skel);
	static inline void detach(struct map_perf_test2_bpf *skel);
	static inline void destroy(struct map_perf_test2_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
map_perf_test2_bpf__destroy(struct map_perf_test2_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
map_perf_test2_bpf__create_skeleton(struct map_perf_test2_bpf *obj);

static inline struct map_perf_test2_bpf *
map_perf_test2_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct map_perf_test2_bpf *obj;
	int err;

	obj = (struct map_perf_test2_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = map_perf_test2_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	map_perf_test2_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct map_perf_test2_bpf *
map_perf_test2_bpf__open(void)
{
	return map_perf_test2_bpf__open_opts(NULL);
}

static inline int
map_perf_test2_bpf__load(struct map_perf_test2_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct map_perf_test2_bpf *
map_perf_test2_bpf__open_and_load(void)
{
	struct map_perf_test2_bpf *obj;
	int err;

	obj = map_perf_test2_bpf__open();
	if (!obj)
		return NULL;
	err = map_perf_test2_bpf__load(obj);
	if (err) {
		map_perf_test2_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
map_perf_test2_bpf__attach(struct map_perf_test2_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
map_perf_test2_bpf__detach(struct map_perf_test2_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *map_perf_test2_bpf__elf_bytes(size_t *sz);

static inline int
map_perf_test2_bpf__create_skeleton(struct map_perf_test2_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "map_perf_test2_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 3;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "pb";
	s->maps[0].map = &obj->maps.pb;

	s->maps[1].name = "heap";
	s->maps[1].map = &obj->maps.heap;

	s->maps[2].name = "map_perf.rodata";
	s->maps[2].map = &obj->maps.rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "map_perf_test";
	s->progs[0].prog = &obj->progs.map_perf_test;
	s->progs[0].link = &obj->links.map_perf_test;

	s->data = map_perf_test2_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *map_perf_test2_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x48\x0b\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0a\0\
\x01\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x70\x65\
\x72\x66\x5f\x65\x76\x65\x6e\x74\0\x2e\x6d\x61\x70\x73\0\x2e\x72\x6f\x64\x61\
\x74\x61\0\x6c\x69\x63\x65\x6e\x73\x65\0\x6d\x61\x70\x5f\x70\x65\x72\x66\x5f\
\x74\x65\x73\x74\x32\x2e\x62\x70\x66\x2e\x63\0\x4c\x42\x42\x30\x5f\x31\0\x4c\
\x42\x42\x30\x5f\x33\0\x6d\x61\x70\x5f\x70\x65\x72\x66\x5f\x74\x65\x73\x74\x2e\
\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x6d\x61\x70\x5f\x70\x65\x72\x66\x5f\x74\x65\x73\
\x74\0\x70\x62\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x68\x65\x61\x70\0\x2e\x72\
\x65\x6c\x70\x65\x72\x66\x5f\x65\x76\x65\x6e\x74\0\x2e\x42\x54\x46\0\x2e\x42\
\x54\x46\x2e\x65\x78\x74\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x32\0\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x47\0\0\0\0\0\x03\0\xa8\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x4e\0\0\0\0\0\x03\0\x70\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x55\0\0\0\x01\0\
\x05\0\0\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x6b\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x70\x01\0\0\0\0\0\0\x79\0\
\0\0\x11\0\x04\0\0\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x7c\0\0\0\x11\0\x06\0\0\0\0\
\0\0\0\0\0\x04\0\0\0\0\0\0\0\x85\0\0\0\x11\0\x04\0\x20\0\0\0\0\0\0\0\x20\0\0\0\
\0\0\0\0\x85\0\0\0\x0e\0\0\0\x63\x0a\xfc\xff\0\0\0\0\xb7\x01\0\0\x01\0\0\0\x7b\
\x1a\xf0\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\xbf\xa3\0\
\0\0\0\0\0\x07\x03\0\0\xf0\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\
\x04\0\0\0\0\0\0\x85\0\0\0\x02\0\0\0\xb7\x06\0\0\x0a\0\0\0\x05\0\x07\0\0\0\0\0\
\x07\x06\0\0\xff\xff\xff\xff\xbf\x61\0\0\0\0\0\0\x67\x01\0\0\x20\0\0\0\x77\x01\
\0\0\x20\0\0\0\x55\x01\x02\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\xbf\
\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x85\0\0\0\x01\0\0\0\x7b\x0a\xe8\xff\0\0\0\0\x15\0\xf2\xff\0\0\0\0\x61\xa3\
\xfc\xff\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x18\0\0\0\xbf\
\x04\0\0\0\0\0\0\x85\0\0\0\x06\0\0\0\x79\xa1\xe8\xff\0\0\0\0\x07\x01\0\0\x08\0\
\0\0\x7b\x1a\xe8\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\
\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xe8\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\xb7\x04\0\0\x02\0\0\0\x85\0\0\0\x02\0\0\0\x05\0\xe0\xff\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6b\x65\x79\x3a\x20\x25\x64\x20\x09\
\x20\x76\x61\x6c\x75\x65\x3a\x20\x25\x6c\x64\x20\x0a\x20\0\x47\x50\x4c\0\0\0\0\
\0\x40\0\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\xb8\0\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\
\xe8\0\0\0\0\0\0\0\x01\0\0\0\x06\0\0\0\x48\x01\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\
\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\xfc\x02\0\0\xfc\x02\0\0\xd3\x02\0\0\0\0\0\0\0\
\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\
\0\0\0\0\x02\0\0\0\x04\0\0\0\x02\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\
\0\0\0\0\0\0\0\x02\x06\0\0\0\x19\0\0\0\0\0\0\x08\x07\0\0\0\x1d\0\0\0\0\0\0\x08\
\x08\0\0\0\x23\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x0a\0\0\0\
\x30\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\x01\0\0\0\0\0\0\0\x02\x0c\0\0\0\0\0\0\0\
\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\xe8\x03\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\
\0\x35\0\0\0\x01\0\0\0\0\0\0\0\x3a\0\0\0\x05\0\0\0\x40\0\0\0\x3e\0\0\0\x09\0\0\
\0\x80\0\0\0\x44\0\0\0\x0b\0\0\0\xc0\0\0\0\x50\0\0\0\0\0\0\x0e\x0d\0\0\0\x01\0\
\0\0\0\0\0\0\0\0\0\x02\x10\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\
\x06\0\0\0\0\0\0\0\0\0\0\x02\x12\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\0\0\0\0\0\0\0\x02\x15\0\0\0\x53\0\
\0\0\x03\0\0\x04\x14\x02\0\0\x59\0\0\0\x02\0\0\0\0\0\0\0\x5d\0\0\0\x17\0\0\0\
\x20\0\0\0\x62\0\0\0\x18\0\0\0\xa0\0\0\0\x6b\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\
\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x16\0\0\0\x04\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\x03\
\0\0\0\0\x16\0\0\0\x04\0\0\0\0\x02\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\x35\0\0\0\
\x0f\0\0\0\0\0\0\0\x44\0\0\0\x11\0\0\0\x40\0\0\0\x3a\0\0\0\x13\0\0\0\x80\0\0\0\
\x3e\0\0\0\x14\0\0\0\xc0\0\0\0\x70\0\0\0\0\0\0\x0e\x19\0\0\0\x01\0\0\0\0\0\0\0\
\0\0\0\x02\0\0\0\0\0\0\0\0\x01\0\0\x0d\x02\0\0\0\x75\0\0\0\x1b\0\0\0\x79\0\0\0\
\x01\0\0\x0c\x1c\0\0\0\0\0\0\0\0\0\0\x0a\x16\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\
\x1e\0\0\0\x04\0\0\0\x18\0\0\0\x87\0\0\0\0\0\0\x0e\x1f\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x03\0\0\0\0\x16\0\0\0\x04\0\0\0\x04\0\0\0\x9d\0\0\0\0\0\0\x0e\x21\0\0\0\
\x01\0\0\0\xb2\x02\0\0\x02\0\0\x0f\x40\0\0\0\x0e\0\0\0\0\0\0\0\x20\0\0\0\x1a\0\
\0\0\x20\0\0\0\x20\0\0\0\xb8\x02\0\0\x01\0\0\x0f\x18\0\0\0\x20\0\0\0\0\0\0\0\
\x18\0\0\0\xc0\x02\0\0\x01\0\0\x0f\x04\0\0\0\x22\0\0\0\0\0\0\0\x04\0\0\0\0\x69\
\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\
\x5f\x5f\0\x75\x33\x32\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\
\x20\x69\x6e\x74\0\x6c\x6f\x6e\x67\0\x74\x79\x70\x65\0\x6b\x65\x79\0\x76\x61\
\x6c\x75\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x70\x62\0\x65\x76\
\x65\x6e\x74\0\x70\x69\x64\0\x63\x6f\x6d\x6d\0\x66\x69\x6c\x65\x6e\x61\x6d\x65\
\0\x63\x68\x61\x72\0\x68\x65\x61\x70\0\x63\x74\x78\0\x6d\x61\x70\x5f\x70\x65\
\x72\x66\x5f\x74\x65\x73\x74\0\x6d\x61\x70\x5f\x70\x65\x72\x66\x5f\x74\x65\x73\
\x74\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x2f\
\x68\x6f\x6d\x65\x2f\x70\x72\x69\x79\x61\x2f\x6c\x69\x62\x62\x70\x66\x2d\x62\
\x6f\x6f\x74\x73\x74\x72\x61\x70\x2f\x65\x78\x61\x6d\x70\x6c\x65\x73\x2f\x63\
\x2f\x6d\x61\x70\x5f\x70\x65\x72\x66\x5f\x74\x65\x73\x74\x32\x2e\x62\x70\x66\
\x2e\x63\0\x20\x20\x20\x20\x20\x20\x20\x20\x75\x33\x32\x20\x6b\x65\x79\x20\x3d\
\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x70\x69\
\x64\x5f\x74\x67\x69\x64\x28\x29\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\x6c\x6f\
\x6e\x67\x20\x69\x6e\x69\x74\x5f\x76\x61\x6c\x20\x3d\x20\x31\x3b\0\x20\x20\x20\
\x20\x20\x20\x20\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x75\x70\x64\x61\x74\x65\
\x5f\x65\x6c\x65\x6d\x28\x26\x70\x62\x2c\x20\x26\x6b\x65\x79\x2c\x20\x26\x69\
\x6e\x69\x74\x5f\x76\x61\x6c\x2c\x20\x42\x50\x46\x5f\x41\x4e\x59\x29\x3b\0\x20\
\x20\x20\x20\x20\x20\x20\x20\x66\x6f\x72\x20\x28\x69\x20\x3d\x20\x30\x3b\x20\
\x69\x20\x3c\x20\x31\x30\x3b\x20\x69\x2b\x2b\x29\x20\x7b\0\x20\x20\x20\x20\x20\
\x20\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x30\x3b\0\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x20\x20\x20\x20\x20\x76\x61\x6c\x75\x65\x20\x3d\x20\x62\x70\
\x66\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\x65\x6c\x65\x6d\x28\x26\
\x70\x62\x2c\x20\x26\x6b\x65\x79\x29\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x20\x20\x20\x69\x66\x20\x28\x76\x61\x6c\x75\x65\x29\x20\0\x20\
\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x6b\x65\x79\
\x3a\x20\x25\x64\x20\x5c\x74\x20\x76\x61\x6c\x75\x65\x3a\x20\x25\x6c\x64\x20\
\x5c\x6e\x20\x22\x2c\x20\x6b\x65\x79\x2c\x20\x76\x61\x6c\x75\x65\x29\x3b\0\x20\
\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x76\x61\x6c\x75\x65\x3d\x76\x61\x6c\x75\x65\x2b\x31\x3b\x20\
\x20\0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x20\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x75\x70\x64\x61\x74\
\x65\x5f\x65\x6c\x65\x6d\x28\x26\x70\x62\x2c\x20\x26\x6b\x65\x79\x2c\x20\x26\
\x76\x61\x6c\x75\x65\x2c\x20\x42\x50\x46\x5f\x45\x58\x49\x53\x54\x29\x3b\0\x2e\
\x6d\x61\x70\x73\0\x2e\x72\x6f\x64\x61\x74\x61\0\x6c\x69\x63\x65\x6e\x73\x65\0\
\x70\x65\x72\x66\x5f\x65\x76\x65\x6e\x74\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\
\x14\0\0\0\x14\0\0\0\x2c\x01\0\0\x40\x01\0\0\0\0\0\0\x08\0\0\0\xc8\x02\0\0\x01\
\0\0\0\0\0\0\0\x1d\0\0\0\x10\0\0\0\xc8\x02\0\0\x12\0\0\0\0\0\0\0\xa6\0\0\0\xe3\
\0\0\0\x13\x90\0\0\x08\0\0\0\xa6\0\0\0\xe3\0\0\0\x0d\x90\0\0\x18\0\0\0\xa6\0\0\
\0\x11\x01\0\0\x0e\x94\0\0\x28\0\0\0\xa6\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\xa6\0\
\0\0\x2c\x01\0\0\x09\xa4\0\0\x70\0\0\0\xa6\0\0\0\x68\x01\0\0\x17\xac\0\0\x90\0\
\0\0\xa6\0\0\0\x68\x01\0\0\x09\xac\0\0\x98\0\0\0\xa6\0\0\0\x8b\x01\0\0\x09\x40\
\x01\0\xb0\0\0\0\xa6\0\0\0\0\0\0\0\0\0\0\0\xb8\0\0\0\xa6\0\0\0\x9d\x01\0\0\x19\
\xb0\0\0\xd0\0\0\0\xa6\0\0\0\x9d\x01\0\0\x17\xb0\0\0\xd8\0\0\0\xa6\0\0\0\xd5\
\x01\0\0\x15\xb4\0\0\xe0\0\0\0\xa6\0\0\0\xf1\x01\0\0\x19\xc0\0\0\x10\x01\0\0\
\xa6\0\0\0\x3e\x02\0\0\x1f\xc4\0\0\x18\x01\0\0\xa6\0\0\0\x3e\x02\0\0\x24\xc4\0\
\0\x20\x01\0\0\xa6\0\0\0\x3e\x02\0\0\x1e\xc4\0\0\x30\x01\0\0\xa6\0\0\0\0\0\0\0\
\0\0\0\0\x48\x01\0\0\xa6\0\0\0\x67\x02\0\0\x19\xc8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x03\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x40\0\0\0\0\0\0\0\xa7\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x09\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe8\0\0\0\0\0\0\
\0\x08\x01\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\
\x11\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf0\x01\0\0\0\0\0\0\x70\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1c\0\0\0\
\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\x03\0\0\0\0\0\0\x40\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x22\0\0\0\x01\0\0\0\x02\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x03\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2a\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\xb8\x03\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x8a\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\xc0\x03\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x02\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\x99\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\
\0\0\0\0\0\xe7\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x9e\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe8\x09\0\0\0\0\0\0\x60\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct map_perf_test2_bpf *map_perf_test2_bpf::open(const struct bpf_object_open_opts *opts) { return map_perf_test2_bpf__open_opts(opts); }
struct map_perf_test2_bpf *map_perf_test2_bpf::open_and_load() { return map_perf_test2_bpf__open_and_load(); }
int map_perf_test2_bpf::load(struct map_perf_test2_bpf *skel) { return map_perf_test2_bpf__load(skel); }
int map_perf_test2_bpf::attach(struct map_perf_test2_bpf *skel) { return map_perf_test2_bpf__attach(skel); }
void map_perf_test2_bpf::detach(struct map_perf_test2_bpf *skel) { map_perf_test2_bpf__detach(skel); }
void map_perf_test2_bpf::destroy(struct map_perf_test2_bpf *skel) { map_perf_test2_bpf__destroy(skel); }
const void *map_perf_test2_bpf::elf_bytes(size_t *sz) { return map_perf_test2_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
map_perf_test2_bpf__assert(struct map_perf_test2_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __MAP_PERF_TEST2_BPF_SKEL_H__ */
