/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __MINIMAL_LEGACY_BPF_SKEL_H__
#define __MINIMAL_LEGACY_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct minimal_legacy_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *my_pid_map;
		struct bpf_map *rodata_str1_1;
	} maps;
	struct {
		struct bpf_program *handle_tp;
	} progs;
	struct {
		struct bpf_link *handle_tp;
	} links;

#ifdef __cplusplus
	static inline struct minimal_legacy_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct minimal_legacy_bpf *open_and_load();
	static inline int load(struct minimal_legacy_bpf *skel);
	static inline int attach(struct minimal_legacy_bpf *skel);
	static inline void detach(struct minimal_legacy_bpf *skel);
	static inline void destroy(struct minimal_legacy_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
minimal_legacy_bpf__destroy(struct minimal_legacy_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
minimal_legacy_bpf__create_skeleton(struct minimal_legacy_bpf *obj);

static inline struct minimal_legacy_bpf *
minimal_legacy_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct minimal_legacy_bpf *obj;
	int err;

	obj = (struct minimal_legacy_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = minimal_legacy_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	minimal_legacy_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct minimal_legacy_bpf *
minimal_legacy_bpf__open(void)
{
	return minimal_legacy_bpf__open_opts(NULL);
}

static inline int
minimal_legacy_bpf__load(struct minimal_legacy_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct minimal_legacy_bpf *
minimal_legacy_bpf__open_and_load(void)
{
	struct minimal_legacy_bpf *obj;
	int err;

	obj = minimal_legacy_bpf__open();
	if (!obj)
		return NULL;
	err = minimal_legacy_bpf__load(obj);
	if (err) {
		minimal_legacy_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
minimal_legacy_bpf__attach(struct minimal_legacy_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
minimal_legacy_bpf__detach(struct minimal_legacy_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *minimal_legacy_bpf__elf_bytes(size_t *sz);

static inline int
minimal_legacy_bpf__create_skeleton(struct minimal_legacy_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "minimal_legacy_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 2;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "my_pid_map";
	s->maps[0].map = &obj->maps.my_pid_map;

	s->maps[1].name = ".rodata.str1.1";
	s->maps[1].map = &obj->maps.rodata_str1_1;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "handle_tp";
	s->progs[0].prog = &obj->progs.handle_tp;
	s->progs[0].link = &obj->links.handle_tp;

	s->data = minimal_legacy_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *minimal_legacy_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x58\x07\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0a\0\
\x01\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x74\x70\
\x2f\x73\x79\x73\x63\x61\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\
\x5f\x77\x72\x69\x74\x65\0\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x6d\x61\x70\x73\0\
\x2e\x72\x6f\x64\x61\x74\x61\x2e\x73\x74\x72\x31\x2e\x31\0\x6d\x69\x6e\x69\x6d\
\x61\x6c\x5f\x6c\x65\x67\x61\x63\x79\x2e\x62\x70\x66\x2e\x63\0\x4c\x42\x42\x30\
\x5f\x33\0\x68\x61\x6e\x64\x6c\x65\x5f\x74\x70\0\x6d\x79\x5f\x70\x69\x64\x5f\
\x6d\x61\x70\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x72\x65\x6c\x74\x70\x2f\x73\
\x79\x73\x63\x61\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x77\
\x72\x69\x74\x65\0\x2e\x42\x54\x46\0\x2e\x42\x54\x46\x2e\x65\x78\x74\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4a\0\0\0\x04\0\xf1\xff\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x5f\0\0\0\0\0\x03\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x66\0\0\0\x12\0\
\x03\0\0\0\0\0\0\0\0\0\x08\x01\0\0\0\0\0\0\x70\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\
\0\x20\0\0\0\0\0\0\0\x7b\0\0\0\x11\0\x04\0\0\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\
\xb7\x01\0\0\0\0\0\0\x63\x1a\xfc\xff\0\0\0\0\x85\0\0\0\x0e\0\0\0\xbf\x06\0\0\0\
\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\xbf\x01\0\0\0\0\0\0\xb7\0\0\0\x01\0\0\0\x15\
\x01\x14\0\0\0\0\0\x77\x06\0\0\x20\0\0\0\x61\x11\0\0\0\0\0\0\x5d\x61\x11\0\0\0\
\0\0\xb7\x01\0\0\x64\x2e\x0a\0\x63\x1a\xf8\xff\0\0\0\0\x18\x01\0\0\x6f\x6d\x20\
\x50\0\0\0\0\x49\x44\x20\x25\x7b\x1a\xf0\xff\0\0\0\0\x18\x01\0\0\x67\x65\x72\
\x65\0\0\0\0\x64\x20\x66\x72\x7b\x1a\xe8\xff\0\0\0\0\x18\x01\0\0\x42\x50\x46\
\x20\0\0\0\0\x74\x72\x69\x67\x7b\x1a\xe0\xff\0\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\
\x01\0\0\xe0\xff\xff\xff\xb7\x02\0\0\x1c\0\0\0\xbf\x63\0\0\0\0\0\0\x85\0\0\0\
\x06\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\x42\x53\x44\
\x2f\x47\x50\x4c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x42\x50\x46\x20\x74\x72\x69\x67\x67\x65\x72\x65\x64\x20\x66\x72\x6f\
\x6d\x20\x50\x49\x44\x20\x25\x64\x2e\x0a\0\0\0\0\0\x30\0\0\0\0\0\0\0\x01\0\0\0\
\x05\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x88\x01\0\0\x88\x01\0\0\xbf\x01\0\0\
\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\
\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x02\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\
\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x08\0\0\0\x19\0\0\0\0\0\0\x08\x09\0\0\0\x1d\
\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x0b\0\0\0\x2a\0\0\0\0\0\
\0\x08\x02\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\x30\0\0\0\x01\0\0\0\0\0\0\0\x35\
\0\0\0\x05\0\0\0\x40\0\0\0\x41\0\0\0\x07\0\0\0\x80\0\0\0\x45\0\0\0\x0a\0\0\0\
\xc0\0\0\0\x4b\0\0\0\0\0\0\x0e\x0c\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\
\0\0\0\x01\0\0\x0d\x02\0\0\0\x56\0\0\0\x0e\0\0\0\x5a\0\0\0\x01\0\0\x0c\x0f\0\0\
\0\x64\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x11\0\0\
\0\x04\0\0\0\x0d\0\0\0\x69\0\0\0\0\0\0\x0e\x12\0\0\0\x01\0\0\0\x95\x01\0\0\x01\
\0\0\x0f\x0d\0\0\0\x13\0\0\0\0\0\0\0\x0d\0\0\0\x9d\x01\0\0\x01\0\0\x0f\x20\0\0\
\0\x0d\0\0\0\0\0\0\0\x20\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\
\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x75\x33\x32\0\x75\x6e\x73\x69\
\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x70\x69\x64\x5f\x74\0\x74\x79\x70\x65\0\x6d\
\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\x61\x6c\x75\x65\0\
\x6d\x79\x5f\x70\x69\x64\x5f\x6d\x61\x70\0\x63\x74\x78\0\x68\x61\x6e\x64\x6c\
\x65\x5f\x74\x70\0\x63\x68\x61\x72\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2f\x68\x6f\
\x6d\x65\x2f\x70\x72\x69\x79\x61\x2f\x6c\x69\x62\x62\x70\x66\x2d\x62\x6f\x6f\
\x74\x73\x74\x72\x61\x70\x2f\x65\x78\x61\x6d\x70\x6c\x65\x73\x2f\x63\x2f\x6d\
\x69\x6e\x69\x6d\x61\x6c\x5f\x6c\x65\x67\x61\x63\x79\x2e\x62\x70\x66\x2e\x63\0\
\x69\x6e\x74\x20\x68\x61\x6e\x64\x6c\x65\x5f\x74\x70\x28\x76\x6f\x69\x64\x20\
\x2a\x63\x74\x78\x29\0\x09\x75\x33\x32\x20\x69\x6e\x64\x65\x78\x20\x3d\x20\x30\
\x3b\0\x09\x70\x69\x64\x5f\x74\x20\x70\x69\x64\x20\x3d\x20\x62\x70\x66\x5f\x67\
\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\
\x28\x29\x20\x3e\x3e\x20\x33\x32\x3b\0\x09\x70\x69\x64\x5f\x74\x20\x2a\x6d\x79\
\x5f\x70\x69\x64\x20\x3d\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\
\x75\x70\x5f\x65\x6c\x65\x6d\x28\x26\x6d\x79\x5f\x70\x69\x64\x5f\x6d\x61\x70\
\x2c\x20\x26\x69\x6e\x64\x65\x78\x29\x3b\0\x09\x69\x66\x20\x28\x21\x6d\x79\x5f\
\x70\x69\x64\x20\x7c\x7c\x20\x2a\x6d\x79\x5f\x70\x69\x64\x20\x21\x3d\x20\x70\
\x69\x64\x29\0\x09\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x42\x50\x46\
\x20\x74\x72\x69\x67\x67\x65\x72\x65\x64\x20\x66\x72\x6f\x6d\x20\x50\x49\x44\
\x20\x25\x64\x2e\x5c\x6e\x22\x2c\x20\x70\x69\x64\x29\x3b\0\x7d\0\x6c\x69\x63\
\x65\x6e\x73\x65\0\x2e\x6d\x61\x70\x73\0\x74\x70\x2f\x73\x79\x73\x63\x61\x6c\
\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x77\x72\x69\x74\x65\0\0\
\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\xbc\0\0\0\xd0\0\0\0\0\0\0\
\0\x08\0\0\0\xa3\x01\0\0\x01\0\0\0\0\0\0\0\x10\0\0\0\x10\0\0\0\xa3\x01\0\0\x0b\
\0\0\0\0\0\0\0\x71\0\0\0\xae\0\0\0\0\x58\0\0\x08\0\0\0\x71\0\0\0\xc7\0\0\0\x06\
\x60\0\0\x10\0\0\0\x71\0\0\0\xd7\0\0\0\x0e\x64\0\0\x28\0\0\0\x71\0\0\0\0\0\0\0\
\0\0\0\0\x30\0\0\0\x71\0\0\0\x06\x01\0\0\x12\x68\0\0\x58\0\0\0\x71\0\0\0\x41\
\x01\0\0\x0e\x70\0\0\x60\0\0\0\x71\0\0\0\0\0\0\0\0\0\0\0\x68\0\0\0\x71\0\0\0\
\x41\x01\0\0\x11\x70\0\0\x70\0\0\0\x71\0\0\0\x41\x01\0\0\x06\x70\0\0\x80\0\0\0\
\x71\0\0\0\x61\x01\0\0\x02\x7c\0\0\0\x01\0\0\x71\0\0\0\x93\x01\0\0\x01\x88\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x03\0\0\0\x20\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\xb1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x09\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\xf8\0\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\
\0\x18\0\0\0\0\0\0\0\x11\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\
\x01\0\0\0\0\0\0\x08\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x2d\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa8\x02\0\0\0\0\
\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x35\0\
\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb8\x02\0\0\0\0\0\0\x20\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3b\0\0\0\x01\0\0\0\
\x32\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd8\x02\0\0\0\0\0\0\x1c\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x83\0\0\0\x09\0\0\0\x40\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xf8\x02\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x02\0\0\0\x03\0\0\
\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\xa3\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x08\x03\0\0\0\0\0\0\x5f\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\xa8\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x68\x06\0\0\0\0\0\0\xf0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct minimal_legacy_bpf *minimal_legacy_bpf::open(const struct bpf_object_open_opts *opts) { return minimal_legacy_bpf__open_opts(opts); }
struct minimal_legacy_bpf *minimal_legacy_bpf::open_and_load() { return minimal_legacy_bpf__open_and_load(); }
int minimal_legacy_bpf::load(struct minimal_legacy_bpf *skel) { return minimal_legacy_bpf__load(skel); }
int minimal_legacy_bpf::attach(struct minimal_legacy_bpf *skel) { return minimal_legacy_bpf__attach(skel); }
void minimal_legacy_bpf::detach(struct minimal_legacy_bpf *skel) { minimal_legacy_bpf__detach(skel); }
void minimal_legacy_bpf::destroy(struct minimal_legacy_bpf *skel) { minimal_legacy_bpf__destroy(skel); }
const void *minimal_legacy_bpf::elf_bytes(size_t *sz) { return minimal_legacy_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
minimal_legacy_bpf__assert(struct minimal_legacy_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __MINIMAL_LEGACY_BPF_SKEL_H__ */
