/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __REPRODUCE_BPF_SKEL_H__
#define __REPRODUCE_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct reproduce_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *func;
	} progs;
	struct {
		struct bpf_link *func;
	} links;

#ifdef __cplusplus
	static inline struct reproduce_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct reproduce_bpf *open_and_load();
	static inline int load(struct reproduce_bpf *skel);
	static inline int attach(struct reproduce_bpf *skel);
	static inline void detach(struct reproduce_bpf *skel);
	static inline void destroy(struct reproduce_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
reproduce_bpf__destroy(struct reproduce_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
reproduce_bpf__create_skeleton(struct reproduce_bpf *obj);

static inline struct reproduce_bpf *
reproduce_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct reproduce_bpf *obj;
	int err;

	obj = (struct reproduce_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = reproduce_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	reproduce_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct reproduce_bpf *
reproduce_bpf__open(void)
{
	return reproduce_bpf__open_opts(NULL);
}

static inline int
reproduce_bpf__load(struct reproduce_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct reproduce_bpf *
reproduce_bpf__open_and_load(void)
{
	struct reproduce_bpf *obj;
	int err;

	obj = reproduce_bpf__open();
	if (!obj)
		return NULL;
	err = reproduce_bpf__load(obj);
	if (err) {
		reproduce_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
reproduce_bpf__attach(struct reproduce_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
reproduce_bpf__detach(struct reproduce_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *reproduce_bpf__elf_bytes(size_t *sz);

static inline int
reproduce_bpf__create_skeleton(struct reproduce_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "reproduce_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "reproduc.rodata";
	s->maps[0].map = &obj->maps.rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "func";
	s->progs[0].prog = &obj->progs.func;
	s->progs[0].link = &obj->links.func;

	s->data = reproduce_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *reproduce_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x48\x0a\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x09\0\
\x01\0\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x70\x65\
\x72\x66\x5f\x65\x76\x65\x6e\x74\0\x2e\x72\x6f\x64\x61\x74\x61\0\x6c\x69\x63\
\x65\x6e\x73\x65\0\x72\x65\x70\x72\x6f\x64\x75\x63\x65\x2e\x62\x70\x66\x2e\x63\
\0\x66\x75\x6e\x63\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x66\x75\x6e\x63\x2e\x5f\
\x5f\x5f\x5f\x66\x6d\x74\x2e\x31\0\x66\x75\x6e\x63\x2e\x5f\x5f\x5f\x5f\x66\x6d\
\x74\x2e\x32\0\x4c\x42\x42\x30\x5f\x32\0\x66\x75\x6e\x63\x2e\x5f\x5f\x5f\x5f\
\x66\x6d\x74\x2e\x33\0\x66\x75\x6e\x63\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\
\x72\x65\x6c\x70\x65\x72\x66\x5f\x65\x76\x65\x6e\x74\0\x2e\x42\x54\x46\0\x2e\
\x42\x54\x46\x2e\x65\x78\x74\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x2c\0\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3c\0\0\0\x01\0\x04\0\0\0\0\0\0\0\0\0\x0e\0\0\0\
\0\0\0\0\x49\0\0\0\x01\0\x04\0\x0e\0\0\0\0\0\0\0\x09\0\0\0\0\0\0\0\x58\0\0\0\
\x01\0\x04\0\x17\0\0\0\0\0\0\0\x0b\0\0\0\0\0\0\0\x67\0\0\0\0\0\x03\0\x20\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x6e\0\0\0\x01\0\x04\0\x22\0\0\0\0\0\0\0\x0c\0\0\0\0\
\0\0\0\0\0\0\0\x03\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x7d\0\0\0\x12\0\x03\
\0\0\0\0\0\0\0\0\0\x30\x01\0\0\0\0\0\0\x82\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\
\x04\0\0\0\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x0e\0\0\0\
\x85\0\0\0\x06\0\0\0\xb7\x01\0\0\0\0\0\0\x7b\x1a\xf8\xff\0\0\0\0\x7b\x1a\xf0\
\xff\0\0\0\0\x7b\x1a\xe8\xff\0\0\0\0\x7b\x1a\xe0\xff\0\0\0\0\x7b\x1a\xd8\xff\0\
\0\0\0\x7b\x1a\xd0\xff\0\0\0\0\x7b\x1a\xc8\xff\0\0\0\0\x85\0\0\0\x23\0\0\0\x7b\
\x0a\xc0\xff\0\0\0\0\xbf\xa6\0\0\0\0\0\0\x07\x06\0\0\xc0\xff\xff\xff\x18\x01\0\
\0\x0e\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x09\0\0\0\xbf\x63\0\0\0\0\0\0\x85\0\0\
\0\x06\0\0\0\x18\x01\0\0\x17\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x0b\0\0\0\xbf\
\x63\0\0\0\0\0\0\x85\0\0\0\x06\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\x01\0\0\xc8\xff\
\xff\xff\xb7\x02\0\0\x01\0\0\0\xbf\x63\0\0\0\0\0\0\x85\0\0\0\x70\0\0\0\x15\0\
\x04\0\0\0\0\0\x18\x01\0\0\x22\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x0c\0\0\0\x85\
\0\0\0\x06\0\0\0\xb7\0\0\0\x42\xb8\x05\0\x95\0\0\0\0\0\0\0\x42\x50\x46\x20\x74\
\x72\x69\x67\x67\x65\x72\x65\x64\0\x76\x36\x20\x69\x73\x20\x25\x70\0\x76\x61\
\x72\x20\x69\x73\x20\x25\x6c\x64\0\x72\x65\x61\x64\x20\x66\x61\x69\x6c\x65\x64\
\0\x47\x50\x4c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\x80\0\0\0\0\0\
\0\0\x01\0\0\0\x08\0\0\0\xa8\0\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\0\x01\0\0\0\0\0\
\0\x01\0\0\0\x08\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\xf4\x02\0\0\xf4\x02\0\0\
\xa0\x02\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\x03\0\0\x04\xb8\0\0\0\x15\0\
\0\0\x03\0\0\0\0\0\0\0\x1a\0\0\0\x06\0\0\0\x40\x05\0\0\x28\0\0\0\x06\0\0\0\x80\
\x05\0\0\x2d\0\0\0\0\0\0\x08\x04\0\0\0\x40\0\0\0\x15\0\0\x04\xa8\0\0\0\x48\0\0\
\0\x05\0\0\0\0\0\0\0\x4c\0\0\0\x05\0\0\0\x40\0\0\0\x50\0\0\0\x05\0\0\0\x80\0\0\
\0\x54\0\0\0\x05\0\0\0\xc0\0\0\0\x58\0\0\0\x05\0\0\0\0\x01\0\0\x5b\0\0\0\x05\0\
\0\0\x40\x01\0\0\x5e\0\0\0\x05\0\0\0\x80\x01\0\0\x62\0\0\0\x05\0\0\0\xc0\x01\0\
\0\x66\0\0\0\x05\0\0\0\0\x02\0\0\x69\0\0\0\x05\0\0\0\x40\x02\0\0\x6c\0\0\0\x05\
\0\0\0\x80\x02\0\0\x6f\0\0\0\x05\0\0\0\xc0\x02\0\0\x72\0\0\0\x05\0\0\0\0\x03\0\
\0\x75\0\0\0\x05\0\0\0\x40\x03\0\0\x78\0\0\0\x05\0\0\0\x80\x03\0\0\x7b\0\0\0\
\x05\0\0\0\xc0\x03\0\0\x83\0\0\0\x05\0\0\0\0\x04\0\0\x86\0\0\0\x05\0\0\0\x40\
\x04\0\0\x89\0\0\0\x05\0\0\0\x80\x04\0\0\x8f\0\0\0\x05\0\0\0\xc0\x04\0\0\x92\0\
\0\0\x05\0\0\0\0\x05\0\0\x95\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\xa3\0\0\0\0\0\
\0\x08\x07\0\0\0\xa9\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x01\0\0\x0d\
\x09\0\0\0\xbc\0\0\0\x01\0\0\0\xc0\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\xc4\0\
\0\0\x01\0\0\x0c\x08\0\0\0\0\0\0\0\0\0\0\x0a\x0c\0\0\0\xc9\0\0\0\0\0\0\x01\x01\
\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x0b\0\0\0\x0e\0\0\0\x0e\0\0\0\xce\
\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\xe2\0\0\0\0\0\0\x0e\x0d\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x03\0\0\0\0\x0b\0\0\0\x0e\0\0\0\x09\0\0\0\xef\0\0\0\0\0\0\x0e\x10\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x0b\0\0\0\x0e\0\0\0\x0b\0\0\0\xfe\0\0\0\
\0\0\0\x0e\x12\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x0b\0\0\0\x0e\0\0\0\x0c\
\0\0\0\x0d\x01\0\0\0\0\0\x0e\x14\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x0c\0\
\0\0\x0e\0\0\0\x04\0\0\0\x1c\x01\0\0\0\0\0\x0e\x16\0\0\0\x01\0\0\0\x85\x02\0\0\
\x04\0\0\x0f\x2e\0\0\0\x0f\0\0\0\0\0\0\0\x0e\0\0\0\x11\0\0\0\x0e\0\0\0\x09\0\0\
\0\x13\0\0\0\x17\0\0\0\x0b\0\0\0\x15\0\0\0\x22\0\0\0\x0c\0\0\0\x8d\x02\0\0\x01\
\0\0\x0f\x04\0\0\0\x17\0\0\0\0\0\0\0\x04\0\0\0\0\x62\x70\x66\x5f\x70\x65\x72\
\x66\x5f\x65\x76\x65\x6e\x74\x5f\x64\x61\x74\x61\0\x72\x65\x67\x73\0\x73\x61\
\x6d\x70\x6c\x65\x5f\x70\x65\x72\x69\x6f\x64\0\x61\x64\x64\x72\0\x62\x70\x66\
\x5f\x75\x73\x65\x72\x5f\x70\x74\x5f\x72\x65\x67\x73\x5f\x74\0\x70\x74\x5f\x72\
\x65\x67\x73\0\x72\x31\x35\0\x72\x31\x34\0\x72\x31\x33\0\x72\x31\x32\0\x62\x70\
\0\x62\x78\0\x72\x31\x31\0\x72\x31\x30\0\x72\x39\0\x72\x38\0\x61\x78\0\x63\x78\
\0\x64\x78\0\x73\x69\0\x64\x69\0\x6f\x72\x69\x67\x5f\x61\x78\0\x69\x70\0\x63\
\x73\0\x66\x6c\x61\x67\x73\0\x73\x70\0\x73\x73\0\x75\x6e\x73\x69\x67\x6e\x65\
\x64\x20\x6c\x6f\x6e\x67\0\x5f\x5f\x75\x36\x34\0\x75\x6e\x73\x69\x67\x6e\x65\
\x64\x20\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x63\x74\x78\0\x69\x6e\x74\0\x66\
\x75\x6e\x63\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\
\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x66\x75\x6e\x63\x2e\x5f\x5f\x5f\x5f\x66\x6d\
\x74\0\x66\x75\x6e\x63\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\x2e\x31\0\x66\x75\x6e\
\x63\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\x2e\x32\0\x66\x75\x6e\x63\x2e\x5f\x5f\x5f\
\x5f\x66\x6d\x74\x2e\x33\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x2f\x68\x6f\x6d\
\x65\x2f\x70\x72\x69\x79\x61\x2f\x6c\x69\x62\x62\x70\x66\x2d\x62\x6f\x6f\x74\
\x73\x74\x72\x61\x70\x2f\x65\x78\x61\x6d\x70\x6c\x65\x73\x2f\x63\x2f\x72\x65\
\x70\x72\x6f\x64\x75\x63\x65\x2e\x62\x70\x66\x2e\x63\0\x20\x20\x20\x20\x20\x20\
\x20\x20\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x42\x50\x46\x20\x74\
\x72\x69\x67\x67\x65\x72\x65\x64\x22\x29\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\
\x63\x68\x61\x72\x20\x76\x30\x5b\x35\x36\x5d\x20\x3d\x20\x7b\x7d\x3b\0\x20\x20\
\x20\x20\x20\x20\x20\x20\x75\x69\x6e\x74\x36\x34\x5f\x74\x20\x76\x36\x20\x3d\
\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x74\x61\
\x73\x6b\x28\x29\x3b\0\x09\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x76\
\x36\x20\x69\x73\x20\x25\x70\x22\x2c\x20\x76\x37\x29\x3b\0\x09\x62\x70\x66\x5f\
\x70\x72\x69\x6e\x74\x6b\x28\x22\x76\x61\x72\x20\x69\x73\x20\x25\x6c\x64\x22\
\x2c\x20\x76\x61\x72\x29\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x69\x66\x28\x62\x70\x66\x5f\x70\x72\x6f\x62\x65\x5f\x72\x65\
\x61\x64\x5f\x75\x73\x65\x72\x28\x76\x30\x2c\x20\x76\x35\x2c\x26\x76\x36\x29\
\x29\0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\
\x20\x20\x20\x20\x20\x20\x62\x70\x66\x5f\x70\x72\x69\x6e\x74\x6b\x28\x22\x72\
\x65\x61\x64\x20\x66\x61\x69\x6c\x65\x64\x22\x29\x3b\0\x20\x20\x20\x20\x20\x20\
\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x33\x37\x34\x38\x35\x30\x3b\0\x2e\x72\x6f\
\x64\x61\x74\x61\0\x6c\x69\x63\x65\x6e\x73\x65\0\x70\x65\x72\x66\x5f\x65\x76\
\x65\x6e\x74\0\0\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\xcc\
\0\0\0\xe0\0\0\0\0\0\0\0\x08\0\0\0\x95\x02\0\0\x01\0\0\0\0\0\0\0\x0a\0\0\0\x10\
\0\0\0\x95\x02\0\0\x0c\0\0\0\0\0\0\0\x25\x01\0\0\x5d\x01\0\0\x09\x28\0\0\x28\0\
\0\0\x25\x01\0\0\x82\x01\0\0\x0e\x30\0\0\x60\0\0\0\x25\x01\0\0\x9c\x01\0\0\x17\
\x34\0\0\x68\0\0\0\x25\x01\0\0\x9c\x01\0\0\x12\x34\0\0\x78\0\0\0\x25\x01\0\0\0\
\0\0\0\0\0\0\0\x80\0\0\0\x25\x01\0\0\xca\x01\0\0\x02\x44\0\0\xa8\0\0\0\x25\x01\
\0\0\xe7\x01\0\0\x02\x50\0\0\xd8\0\0\0\x25\x01\0\0\0\0\0\0\0\0\0\0\xe0\0\0\0\
\x25\x01\0\0\x07\x02\0\0\x14\x94\0\0\xf8\0\0\0\x25\x01\0\0\x07\x02\0\0\x14\x94\
\0\0\0\x01\0\0\x25\x01\0\0\x3b\x02\0\0\x19\x98\0\0\x20\x01\0\0\x25\x01\0\0\x6e\
\x02\0\0\x09\xa0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\
\0\x03\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\xa8\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x09\0\0\0\x02\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe8\0\0\0\0\0\0\0\x08\x01\0\0\0\0\0\0\x01\0\0\0\0\
\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x11\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\xf0\x01\0\0\0\0\0\0\x30\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1c\0\0\0\x01\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x20\x03\0\0\0\0\0\0\x2e\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x24\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4e\x03\
\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x8b\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x58\x03\0\0\0\0\0\0\
\x40\0\0\0\0\0\0\0\x02\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x9a\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x98\x03\0\0\0\0\0\0\xac\x05\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\x09\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct reproduce_bpf *reproduce_bpf::open(const struct bpf_object_open_opts *opts) { return reproduce_bpf__open_opts(opts); }
struct reproduce_bpf *reproduce_bpf::open_and_load() { return reproduce_bpf__open_and_load(); }
int reproduce_bpf::load(struct reproduce_bpf *skel) { return reproduce_bpf__load(skel); }
int reproduce_bpf::attach(struct reproduce_bpf *skel) { return reproduce_bpf__attach(skel); }
void reproduce_bpf::detach(struct reproduce_bpf *skel) { reproduce_bpf__detach(skel); }
void reproduce_bpf::destroy(struct reproduce_bpf *skel) { reproduce_bpf__destroy(skel); }
const void *reproduce_bpf::elf_bytes(size_t *sz) { return reproduce_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
reproduce_bpf__assert(struct reproduce_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __REPRODUCE_BPF_SKEL_H__ */
